### ISSUE TITLE
units

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf-area#3]
What are the units? Can the user specify them?

**Comment by tmcw** [comment]
Documented as meters squared. I think unit conversion should live outside of this module.

**Comment by morganherlocker** [comment]
>  I think unit conversion should live outside of this module.

My only concern here is that this is a super common use case, and turf-distance turf-buffer are able to do this, so it feels a bit inconsistent. Also, meters are going to give people trouble for large areas.

For example, US area miles => meters:

![](https://dl.dropbox.com/s/ja8qb4z608jimnz/Screenshot%202015-01-15%2013.22.45.png?dl=0)

People will throw that output into QGIS and it will cause zany behavior (I did it myself and was scratching my head for a while before I realized what had happened).
