### ISSUE TITLE
Area for single features returns zeron

### ISSUE THREAD

**Issue by popkinj** [Turfjs/turf-area#4]
The _turf-poygon_ module returns geoJSON like this:

``` json
 {
  "type":"Feature"
  "geometry":
    "type":"Polygon",
    "coordinates":[
        [-129.8886444704388,54.003661492845396],
        [-130.36062119822856,53.63432325944664],
        [-129.63619180208616,53.575708857339734],
        [-129.8886444704388,54.003661492845396]
    ],
    "properties":{}
  }
```

But the _turf-area_ module just returns a zero area with this object. You have to embed the coordinates array within another array to get it to work. Which I'm not totally sure is valid geoJSON for type _Polygon_... Maybe _MultiPolygon_???

For example... I can get the above geoJSON to work by adding another layer of square brackes:

``` json
{
  "type":"Feature"
  "geometry":
    "type":"Polygon",
    "coordinates":[[
      [-129.8886444704388,54.003661492845396],
      [-130.36062119822856,53.63432325944664],
      [-129.63619180208616,53.575708857339734],
      [-129.8886444704388,54.003661492845396]
    ]],
    "properties":{}
  }
```

Is this intended behaviour? Should this issue be under _turf-polygon_ instead?

Thanks ☺

**Comment by morganherlocker** [comment]
Your first polygon is not valid. [Coordinates for polygons should be nested 2 deep](http://geojson.org/geojson-spec.html#id4). The top-level array is an array of rings, where the first ring is the outer hull and all the other rings are holes.

In the first case it looks like you passed an invalid coordinate array to the polygon function. I would recommend validating your geojson using [geojson.io](http://geojson.io/) while debugging. If it will not render in geojson.io, it probably won't work with turf either.

**Comment by popkinj** [comment]
Thanks @morganherlocker . Appreciate the quick response. ☺

My json example above was just "hand balmed" for the sake of the post. The json I was submitting in my code was valid. I have a jsLinter in my build process that catches that sort of thing.

If nesting two deep is the spec... Maybe this is an issue with turf-polygon??? After all it's what's producing the json I'm feeding to turf-area. Should I submit there instead?

**Comment by tmcw** [comment]
turf-polygon requires two-deep json input - see [the example for instance](https://github.com/Turfjs/turf-polygon#example)

**Comment by popkinj** [comment]
Ah... Thanks @tmcw. 
My fault. All good now.

**Comment by popkinj** [comment]
Working like a [charm now](http://yellow-cedar.littleearth.ca.s3-website-us-west-2.amazonaws.com/?zoom=10110&loc=-129.73158%2C53.83047&nodes=%5B%5B-130.30175084133205%2C53.991031751342895%5D%2C%5B-130.0719515581688%2C54.0577867187079%5D%2C%5B-129.75424895331875%2C53.86891605389694%5D%2C%5B-130.1396211597371%2C53.691436074624484%5D%5D&closed=true).
